steps:
  # Step 1: Fetch secrets from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "VITE_FIREBASE_API_KEY=$(gcloud secrets versions access latest --secret=firebase-api-key)" >> /workspace/.build-env
        echo "VITE_FIREBASE_AUTH_DOMAIN=$(gcloud secrets versions access latest --secret=firebase-auth-domain)" >> /workspace/.build-env
        echo "VITE_FIREBASE_PROJECT_ID=$(gcloud secrets versions access latest --secret=firebase-project-id)" >> /workspace/.build-env
        echo "VITE_FIREBASE_STORAGE_BUCKET=$(gcloud secrets versions access latest --secret=firebase-storage-bucket)" >> /workspace/.build-env
        echo "VITE_FIREBASE_MESSAGING_SENDER_ID=$(gcloud secrets versions access latest --secret=firebase-messaging-sender-id)" >> /workspace/.build-env
        echo "VITE_FIREBASE_APP_ID=$(gcloud secrets versions access latest --secret=firebase-app-id)" >> /workspace/.build-env
        echo "VITE_GOOGLE_MAPS_API_KEY=$(gcloud secrets versions access latest --secret=google-maps-api-key)" >> /workspace/.build-env

  # Step 2: Build Docker image with secrets as build args
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/.build-env
        docker build \
          --build-arg VITE_FIREBASE_API_KEY=$$VITE_FIREBASE_API_KEY \
          --build-arg VITE_FIREBASE_AUTH_DOMAIN=$$VITE_FIREBASE_AUTH_DOMAIN \
          --build-arg VITE_FIREBASE_PROJECT_ID=$$VITE_FIREBASE_PROJECT_ID \
          --build-arg VITE_FIREBASE_STORAGE_BUCKET=$$VITE_FIREBASE_STORAGE_BUCKET \
          --build-arg VITE_FIREBASE_MESSAGING_SENDER_ID=$$VITE_FIREBASE_MESSAGING_SENDER_ID \
          --build-arg VITE_FIREBASE_APP_ID=$$VITE_FIREBASE_APP_ID \
          --build-arg VITE_GOOGLE_MAPS_API_KEY=$$VITE_GOOGLE_MAPS_API_KEY \
          --build-arg VITE_APP_ENV=production \
          --build-arg VITE_NAMESPACE=${_STUDENT_NAMESPACE} \
          --build-arg VITE_APP_URL=https://madina-lab-HASH.run.app \
          -t gcr.io/$PROJECT_ID/madina-lab:$COMMIT_SHA \
          -t gcr.io/$PROJECT_ID/madina-lab:latest \
          .

  # Step 3: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/madina-lab:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/madina-lab:latest']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'madina-lab'
      - '--image=gcr.io/$PROJECT_ID/madina-lab:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=3'

  # Step 5: Clean up build env file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'rm -f /workspace/.build-env']

images:
  - 'gcr.io/$PROJECT_ID/madina-lab:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/madina-lab:latest'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _STUDENT_NAMESPACE: ''  # Override per student: --substitutions=_STUDENT_NAMESPACE=alice
