name: "📋 Workshop Feedback"
description: "2 minutes — help us improve future workshops!"
title: "Feedback"
labels: ["feedback"]
body:

  - type: markdown
    attributes:
      value: |
        # 🕌 Workshop Feedback
        **10 quick questions** — your honest feedback shapes future workshops. JazakAllah Khair! 🤲

        ---

  # Q1
  - type: dropdown
    id: overall
    attributes:
      label: "1. How would you rate the workshop overall?"
      options:
        - "⭐⭐⭐⭐⭐ Excellent"
        - "⭐⭐⭐⭐ Good"
        - "⭐⭐⭐ Average"
        - "⭐⭐ Below average"
        - "⭐ Poor"
    validations:
      required: true

  # Q2
  - type: dropdown
    id: favorite-lab
    attributes:
      label: "2. Which lab was your favorite?"
      options:
        - "Lab 1 — Explore GCP Console & meet the app"
        - "Lab 2 — Ship your app (deploy, scan, monitor)"
        - "Lab 3 — Infrastructure as Code (Terraform)"
        - "Enjoyed all equally"
    validations:
      required: true

  # Q3
  - type: dropdown
    id: difficulty
    attributes:
      label: "3. How was the difficulty?"
      options:
        - "Too easy"
        - "Just right"
        - "Slightly hard but I could follow"
        - "Too hard"
    validations:
      required: true

  # Q4
  - type: dropdown
    id: pace
    attributes:
      label: "4. How was the pace?"
      options:
        - "Too fast"
        - "Just right"
        - "Too slow"
    validations:
      required: true

  # Q5
  - type: textarea
    id: liked
    attributes:
      label: "5. What did you like most?"
      placeholder: "Best moment, concept, or part of the workshop..."
    validations:
      required: true

  # Q6
  - type: textarea
    id: disliked
    attributes:
      label: "6. What didn't work well or could be better?"
      placeholder: "Be honest — this helps us the most!"
    validations:
      required: true

  # Q7
  - type: checkboxes
    id: confident
    attributes:
      label: "7. What are you most confident about now? (select all)"
      options:
        - label: "GCP Console & cloud services"
        - label: "Docker & containers"
        - label: "CI/CD pipelines"
        - label: "Security scanning (Hadolint, Trivy, Checkov)"
        - label: "Cloud Run deployment"
        - label: "Terraform / IaC"

  # Q8
  - type: checkboxes
    id: next-topics
    attributes:
      label: "8. What would you like to learn next? (select all)"
      options:
        - label: "Kubernetes"
        - label: "Azure cloud"
        - label: "Advanced CI/CD (GitHub Actions, GitLab)"
        - label: "Monitoring & observability"
        - label: "AI/ML on the cloud"
        - label: "Web development (React, Node.js)"
        - label: "Python & automation"
        - label: "Linux & command line"

  # Q9
  - type: dropdown
    id: recommend
    attributes:
      label: "9. Would you recommend this workshop to others?"
      options:
        - "Definitely yes"
        - "Yes"
        - "Maybe"
        - "No"
    validations:
      required: true

  # Q10
  - type: textarea
    id: anything-else
    attributes:
      label: "10. Anything else?"
      placeholder: "Optional — say whatever's on your mind."